name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    # - name: Publish
    #   run: |
    #     dotnet pack -c Release -o out
    #     dotnet nuget add source  https://nuget.pkg.github.com/ashuaidehao/index.json -n "GitHub" -u ashuaidehao -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    #     dotnet nuget push out/*.nupkg -s "GitHub"

